server:
  port: ${SERVER_PORT:8686}

app:
  vue: ${APP_VUE:http://localhost:8787}

jwt:
  # secret 生产环境请自行生成 UUID
  secret: "43108c53-b756-4f29-8b95-9fca28672d24"
  # token 过期时间（毫秒）默认 8小时
  duration: 28800000

mybatis-flex:
  datasource:
    mysql:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/beidou?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: beidou
      password: beidou
  global-config:
    print-banner: false

# swagger路径：http://localhost:8686/swagger-ui/index.html
springdoc:
  # 生产环境需要关闭这2个参数
  api-docs:
    # 是否开启OpenApi，如果为false，则SwaggerUI也会被禁用
    enabled: ${SPRINGDOC_API_DOCS_ENABLED:false}
  swagger-ui:
    # 是否开启SwaggerUI，依赖OpenApi的开启
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED:false}

spring:
  flyway:
    # 禁用版本验证
    validate-on-migrate: false
  servlet:
    # 默认文件大小就是这里设置的，按需修改
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
  # 禁用Log4j2的JMX功能，防止关闭时出现Unable to unregister MBeans错误
  jmx:
    enabled: false

gms:
  service:
    # zh-CN en-US
    language: zh-CN
    # WZ数据加载策略
    startup:
      # 是否在启动时全量预加载所有WZ数据（如Skill, Quest, CashShop等）
      # true: 预加载模式，启动稍慢，运行时响应快，适合高配置服务器。
      # false: 懒加载模式，启动极快，仅在首次使用时加载数据，适合低配置或开发环境。
      all-wz: true
    rate-limit:
      # 是否开启限流
      enabled: false
      # 每ip多少时间内最大请求数
      limit: 10
      # 每ip最大请求数多少时间重置，单位ms
      duration: 1000
      # 是否自动封禁
      auto-ban: false
    # 公网ip
    wan-host: ${GMS_SERVICE_WAN_HOST:127.0.0.1}
    # 局域网ip
    lan-host: ${GMS_SERVICE_LAN_HOST:127.0.0.1}
    # 本地ip
    localhost: ${GMS_SERVICE_LOCAL_HOST:127.0.0.1}
    # 客户端登录端口
    login-port: ${GMS_SERVICE_LOGIN_PORT:8484}
